services:
  postgres:
    container_name: bot-postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
      shm_size: '256m'
    image: postgres:latest
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: "Asia/Novosibirsk"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 5s
    ports:
      - ${PG_PORT:-5432}:5432